# Generated by Django 3.1.5 on 2021-02-01 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Citizenship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Citizenship',
                'verbose_name_plural': 'Citizenships',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'City',
                'verbose_name_plural': 'Cities',
            },
        ),
        migrations.CreateModel(
            name='Disability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Disability',
                'verbose_name_plural': 'Disabilities',
            },
        ),
        migrations.CreateModel(
            name='MaritalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name': 'Marital Status',
                'verbose_name_plural': 'Marital Statuses',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=64)),
                ('first_name', models.CharField(max_length=64)),
                ('middle_name', models.CharField(max_length=64)),
                ('birth_date', models.DateField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('passport_serial', models.CharField(max_length=64)),
                ('passport_number', models.CharField(max_length=64)),
                ('passport_authority', models.CharField(max_length=64)),
                ('passport_issue_date', models.DateField()),
                ('id_number', models.CharField(max_length=64)),
                ('birth_place', models.CharField(max_length=64)),
                ('living_address', models.CharField(max_length=64)),
                ('home_phone_number', models.CharField(blank=True, max_length=64)),
                ('mobile_phone_number', models.CharField(blank=True, max_length=64)),
                ('email', models.CharField(blank=True, max_length=64, null=True)),
                ('pensioner', models.BooleanField(choices=[(True, 'Yes'), (False, 'No')])),
                ('monthly_income', models.DecimalField(blank=True, decimal_places=4, max_digits=19, null=True)),
                ('citizenship', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clients_citizenship', to='clients.citizenship')),
                ('disability', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clients_disability', to='clients.disability')),
                ('living_place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clients_living_place', to='clients.city')),
                ('marital_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clients_martial_status', to='clients.maritalstatus')),
                ('registration_place', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='clients_registration_place', to='clients.city')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
            },
        ),
    ]
